// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerfectPolicyQuiz.Model;

namespace PerfectPolicyQuiz.Migrations
{
    [DbContext(typeof(QuizContext))]
    [Migration("20220522084718_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PerfectPolicyQuiz.Model.Option", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionLetter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("OptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            OptionId = 1,
                            IsCorrect = true,
                            OptionLetter = "a.",
                            OptionText = "Our Company's SOP - Working at Heights",
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 2,
                            IsCorrect = false,
                            OptionLetter = "b.",
                            OptionText = "Our Company's Privacy Policy",
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 3,
                            IsCorrect = false,
                            OptionLetter = "c.",
                            OptionText = "Our Chemical Safety Data Sheets",
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 4,
                            IsCorrect = false,
                            OptionLetter = "d.",
                            OptionText = "Our Company's Copyright Policy",
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 5,
                            IsCorrect = false,
                            OptionLetter = "e.",
                            OptionText = "Our Company's Purchasing Policy",
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 6,
                            IsCorrect = false,
                            OptionLetter = "a.",
                            OptionText = "Only store in hard copy in a locked filing cabinet",
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 7,
                            IsCorrect = true,
                            OptionLetter = "b.",
                            OptionText = "Store such materials only on our secured network",
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 8,
                            IsCorrect = false,
                            OptionLetter = "c.",
                            OptionText = "Obfuscate it so as to make it difficult to interpret",
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 9,
                            IsCorrect = false,
                            OptionLetter = "d.",
                            OptionText = "Restrict viewing to only admin staff",
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 10,
                            IsCorrect = false,
                            OptionLetter = "e.",
                            OptionText = "Forward to other developers via email",
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 11,
                            IsCorrect = false,
                            OptionLetter = "a.",
                            OptionText = "Should never be viewed by any staff at any level",
                            QuestionId = 3
                        },
                        new
                        {
                            OptionId = 12,
                            IsCorrect = false,
                            OptionLetter = "b.",
                            OptionText = "Can only be viewed by Human Resourses staff",
                            QuestionId = 3
                        },
                        new
                        {
                            OptionId = 13,
                            IsCorrect = true,
                            OptionLetter = "c.",
                            OptionText = "Need to be managed in our company's secured database system",
                            QuestionId = 3
                        },
                        new
                        {
                            OptionId = 14,
                            IsCorrect = false,
                            OptionLetter = "d.",
                            OptionText = "Should only ever be emailed",
                            QuestionId = 3
                        },
                        new
                        {
                            OptionId = 15,
                            IsCorrect = false,
                            OptionLetter = "e.",
                            OptionText = "Should only be stored in hard copy in locked filing cabinets",
                            QuestionId = 3
                        },
                        new
                        {
                            OptionId = 16,
                            IsCorrect = false,
                            OptionLetter = "a.",
                            OptionText = "Note it for later consideration",
                            QuestionId = 4
                        },
                        new
                        {
                            OptionId = 17,
                            IsCorrect = true,
                            OptionLetter = "b.",
                            OptionText = "Report it immediately to an OHS officer",
                            QuestionId = 4
                        },
                        new
                        {
                            OptionId = 18,
                            IsCorrect = false,
                            OptionLetter = "c.",
                            OptionText = "Fill out a Safety Data Sheet",
                            QuestionId = 4
                        },
                        new
                        {
                            OptionId = 19,
                            IsCorrect = false,
                            OptionLetter = "d.",
                            OptionText = "Add it to our Company's Purchasing Policy",
                            QuestionId = 4
                        },
                        new
                        {
                            OptionId = 20,
                            IsCorrect = false,
                            OptionLetter = "e.",
                            OptionText = "Create a new SOP (Safe Operating Procedure)",
                            QuestionId = 4
                        },
                        new
                        {
                            OptionId = 21,
                            IsCorrect = true,
                            OptionLetter = "a.",
                            OptionText = "Request copyright ownership where appropriate and feasible to do so",
                            QuestionId = 5
                        },
                        new
                        {
                            OptionId = 22,
                            IsCorrect = false,
                            OptionLetter = "b.",
                            OptionText = "Only purchase material where we can hold the copyright",
                            QuestionId = 5
                        },
                        new
                        {
                            OptionId = 23,
                            IsCorrect = false,
                            OptionLetter = "c.",
                            OptionText = "Only purchase material where our clients can hold the copyright",
                            QuestionId = 5
                        },
                        new
                        {
                            OptionId = 24,
                            IsCorrect = false,
                            OptionLetter = "d.",
                            OptionText = "Retain a copy of the privacy statement attached to the material purchased",
                            QuestionId = 5
                        },
                        new
                        {
                            OptionId = 25,
                            IsCorrect = false,
                            OptionLetter = "e.",
                            OptionText = "Create a new purchasing policy specific to that purchase",
                            QuestionId = 5
                        },
                        new
                        {
                            OptionId = 26,
                            IsCorrect = false,
                            OptionLetter = "a.",
                            OptionText = "Note it for later consideration",
                            QuestionId = 6
                        },
                        new
                        {
                            OptionId = 27,
                            IsCorrect = false,
                            OptionLetter = "b.",
                            OptionText = "Fill out a Safety Data Sheet",
                            QuestionId = 6
                        },
                        new
                        {
                            OptionId = 28,
                            IsCorrect = false,
                            OptionLetter = "c.",
                            OptionText = "Add it to our Company's Purchasing Policy",
                            QuestionId = 6
                        },
                        new
                        {
                            OptionId = 29,
                            IsCorrect = true,
                            OptionLetter = "d.",
                            OptionText = "Report it immediately to an OHS or security officer",
                            QuestionId = 6
                        },
                        new
                        {
                            OptionId = 30,
                            IsCorrect = false,
                            OptionLetter = "e.",
                            OptionText = "Our Company's Purchasing Policy",
                            QuestionId = 6
                        },
                        new
                        {
                            OptionId = 31,
                            IsCorrect = false,
                            OptionLetter = "a.",
                            OptionText = "Obfuscate it so as to make it difficult to interpret",
                            QuestionId = 7
                        },
                        new
                        {
                            OptionId = 32,
                            IsCorrect = false,
                            OptionLetter = "b.",
                            OptionText = "Restrict viewing to only admin staff",
                            QuestionId = 7
                        },
                        new
                        {
                            OptionId = 33,
                            IsCorrect = false,
                            OptionLetter = "c.",
                            OptionText = "Only store in hard copy in a locked filing cabinet",
                            QuestionId = 7
                        },
                        new
                        {
                            OptionId = 34,
                            IsCorrect = true,
                            OptionLetter = "d.",
                            OptionText = "Store such materials only on our secured network",
                            QuestionId = 7
                        },
                        new
                        {
                            OptionId = 35,
                            IsCorrect = false,
                            OptionLetter = "e.",
                            OptionText = "Forward to other developers via email",
                            QuestionId = 7
                        },
                        new
                        {
                            OptionId = 36,
                            IsCorrect = false,
                            OptionLetter = "a.",
                            OptionText = "Our company's SOP - Working at Heights",
                            QuestionId = 8
                        },
                        new
                        {
                            OptionId = 37,
                            IsCorrect = false,
                            OptionLetter = "b.",
                            OptionText = "Our company's SOP - Vehicle Parking",
                            QuestionId = 8
                        },
                        new
                        {
                            OptionId = 38,
                            IsCorrect = false,
                            OptionLetter = "c.",
                            OptionText = "Our Chemical Safety Data Sheets",
                            QuestionId = 8
                        },
                        new
                        {
                            OptionId = 39,
                            IsCorrect = false,
                            OptionLetter = "d.",
                            OptionText = "Our Company's Copyright Policy",
                            QuestionId = 8
                        },
                        new
                        {
                            OptionId = 40,
                            IsCorrect = true,
                            OptionLetter = "e.",
                            OptionText = "Our company's SOP - Working in a Confined Space",
                            QuestionId = 8
                        },
                        new
                        {
                            OptionId = 41,
                            IsCorrect = true,
                            OptionLetter = "a.",
                            OptionText = "Store such details only on our secured network",
                            QuestionId = 9
                        },
                        new
                        {
                            OptionId = 42,
                            IsCorrect = false,
                            OptionLetter = "b.",
                            OptionText = "Only store in hard copy in a locked filing cabinet",
                            QuestionId = 9
                        },
                        new
                        {
                            OptionId = 43,
                            IsCorrect = false,
                            OptionLetter = "c.",
                            OptionText = "Obfuscate it so as to make it difficult to interpret",
                            QuestionId = 9
                        },
                        new
                        {
                            OptionId = 44,
                            IsCorrect = false,
                            OptionLetter = "d.",
                            OptionText = "Can only be viewed by admin staff",
                            QuestionId = 9
                        },
                        new
                        {
                            OptionId = 45,
                            IsCorrect = false,
                            OptionLetter = "e.",
                            OptionText = "Can be left unsecured",
                            QuestionId = 9
                        },
                        new
                        {
                            OptionId = 46,
                            IsCorrect = false,
                            OptionLetter = "a.",
                            OptionText = "Leave them wherever last used",
                            QuestionId = 10
                        },
                        new
                        {
                            OptionId = 47,
                            IsCorrect = false,
                            OptionLetter = "b.",
                            OptionText = "Place them above the stovetops in the department kitchens",
                            QuestionId = 10
                        },
                        new
                        {
                            OptionId = 48,
                            IsCorrect = true,
                            OptionLetter = "c.",
                            OptionText = "Ensure they are kept appropriately stocked",
                            QuestionId = 10
                        },
                        new
                        {
                            OptionId = 49,
                            IsCorrect = false,
                            OptionLetter = "d.",
                            OptionText = "Only display appropriate signage when directed to do so",
                            QuestionId = 10
                        },
                        new
                        {
                            OptionId = 50,
                            IsCorrect = false,
                            OptionLetter = "e.",
                            OptionText = "Fill out a Safety Data Sheet with each use",
                            QuestionId = 10
                        });
                });

            modelBuilder.Entity("PerfectPolicyQuiz.Model.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("QuestionImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionTopic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            QuestionText = "11. When looking to work at height, Ineed to review:",
                            QuestionTopic = "Working at Heights",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 2,
                            QuestionText = "12. With copyright material from our client:",
                            QuestionTopic = "Client Copyright Materials",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 3,
                            QuestionText = "13. Personal staff details:",
                            QuestionTopic = "Staff Details",
                            QuizId = 3
                        },
                        new
                        {
                            QuestionId = 4,
                            QuestionText = "14. In the event you notice a potential hazard:",
                            QuestionTopic = "Hazards",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 5,
                            QuestionText = "42. When purchasing copyright material from a third party source:",
                            QuestionTopic = "Purchasing Copyright Material",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 6,
                            QuestionText = "56. Should you be involved in or be witness to an OHS-related incident, you should:",
                            QuestionTopic = "Incidents",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 7,
                            QuestionText = "71. With our organisation's copyright material:",
                            QuestionTopic = "Internal Copyright Materials",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 8,
                            QuestionText = "72. When looking to work in a confined space, I need to review:",
                            QuestionTopic = "Confined Space Work",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 9,
                            QuestionText = "82. With Commercial in Confidence Client Details, we are required to:",
                            QuestionTopic = "Client Details",
                            QuizId = 3
                        },
                        new
                        {
                            QuestionId = 10,
                            QuestionText = "87. In relation to the First Aid Kits in the various departments:",
                            QuestionTopic = "First Aid Kit",
                            QuizId = 1
                        });
                });

            modelBuilder.Entity("PerfectPolicyQuiz.Model.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PassPercentage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuizCreatorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuizTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuizTopic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserInfoId")
                        .HasColumnType("int");

                    b.HasKey("QuizId");

                    b.HasIndex("UserInfoId");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            QuizId = 1,
                            CreatingDate = new DateTime(2021, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PassPercentage = "100%",
                            QuizCreatorName = "Steve Jones",
                            QuizTitle = "Perfect Quiz Policy",
                            QuizTopic = "OHS",
                            UserInfoId = 1
                        },
                        new
                        {
                            QuizId = 2,
                            CreatingDate = new DateTime(2021, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PassPercentage = "100%",
                            QuizCreatorName = "Steve Jones",
                            QuizTitle = "Quiz",
                            QuizTopic = "Copyright",
                            UserInfoId = 1
                        },
                        new
                        {
                            QuizId = 3,
                            CreatingDate = new DateTime(2021, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PassPercentage = "100%",
                            QuizCreatorName = "Steve",
                            QuizTitle = "Policy",
                            QuizTopic = "Privacy",
                            UserInfoId = 2
                        });
                });

            modelBuilder.Entity("PerfectPolicyQuiz.Model.UserInfo", b =>
                {
                    b.Property<int>("UserInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserInfoId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserInfoId = 1,
                            Password = "PerfectPolicies!22",
                            UserName = "AdminPerfectPolicies"
                        },
                        new
                        {
                            UserInfoId = 2,
                            Password = "AAA",
                            UserName = "Steve"
                        });
                });

            modelBuilder.Entity("PerfectPolicyQuiz.Model.Option", b =>
                {
                    b.HasOne("PerfectPolicyQuiz.Model.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("PerfectPolicyQuiz.Model.Question", b =>
                {
                    b.HasOne("PerfectPolicyQuiz.Model.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("PerfectPolicyQuiz.Model.Quiz", b =>
                {
                    b.HasOne("PerfectPolicyQuiz.Model.UserInfo", "UserInfo")
                        .WithMany("Quizzes")
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("PerfectPolicyQuiz.Model.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("PerfectPolicyQuiz.Model.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("PerfectPolicyQuiz.Model.UserInfo", b =>
                {
                    b.Navigation("Quizzes");
                });
#pragma warning restore 612, 618
        }
    }
}
